# Generated by Django 5.0.4 on 2024-04-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='Students',
        ),
    ]
