# Generated by Django 5.0.4 on 2024-04-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0002_alter_students_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="student_id",
            field=models.CharField(max_length=10),
        ),
    ]
