# Generated by Django 5.0.4 on 2024-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0003_alter_students_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="student_id",
            field=models.IntegerField(),
        ),
    ]
