# Generated by Django 5.0.4 on 2024-04-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_teacher_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(max_length=30),
        ),
    ]
