# Generated by Django 5.0.6 on 2024-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='about/%Y/%m/%d')),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AboutWorker',
                'ordering': ['firstname'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='about/%Y/%m/%d')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'db_table': 'Company',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Feedback',
                'ordering': ['date'],
            },
        ),
    ]
