# Generated by Django 5.0.6 on 2024-05-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutworker',
            name='picture',
            field=models.ImageField(upload_to='about/%Y/%m/workers'),
        ),
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(upload_to='about/%Y/%m/company'),
        ),
    ]
