# Generated by Django 5.0.4 on 2024-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_rename_movie_id_comment_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
