# Generated by Django 5.0.6 on 2024-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_aboutworker_picture_alter_company_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutworker",
            name="picture",
            field=models.ImageField(upload_to="static/images/workers"),
        ),
        migrations.AlterField(
            model_name="company",
            name="picture",
            field=models.ImageField(upload_to="static/images/company"),
        ),
    ]
