# Generated by Django 5.0.4 on 2024-04-22 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_subject_teacher_subject_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subject',
            name='specialities',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='courses.speciality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ForeignKey(default=-2, on_delete=django.db.models.deletion.CASCADE, to='courses.teacher'),
            preserve_default=False,
        ),
    ]
