# Generated by Django 5.0.4 on 2024-04-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("birthdate", models.DateField()),
                ("gender", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Actors",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("imdb", models.FloatField()),
                ("genre", models.CharField(max_length=100)),
                ("actors", models.ManyToManyField(to="Movies.actor")),
            ],
            options={
                "db_table": "Movie",
            },
        ),
    ]
