# Generated by Django 5.0.4 on 2024-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="Movies.actor"),
        ),
    ]
