# Generated by Django 5.0.4 on 2024-04-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0002_alter_movie_actors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="actors",
        ),
    ]
