# Generated by Django 5.0.4 on 2024-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0003_remove_movie_actors"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="movies",
            field=models.ManyToManyField(to="Movies.movie"),
        ),
    ]
